#include <Arduino.h>

#define OK_BUTTOM_PIN 18

#define FORNT_LEFT_MOTOR_IN1 7
#define FORNT_LEFT_MOTOR_IN2 8
#define FORNT_LEFT_MOTOR_PWM 6
#define FORNT_LEFT_MOTOR_ECA 2
#define FORNT_LEFT_MOTOR_ECB 3

#define FORNT_RIGHT_MOTOR_IN1 26
#define FORNT_RIGHT_MOTOR_IN2 22
#define FORNT_RIGHT_MOTOR_PWM 27
#define FORNT_RIGHT_MOTOR_ECA 4
#define FORNT_RIGHT_MOTOR_ECB 5

#define BACK_LEFT_MOTOR_IN1 11
#define BACK_LEFT_MOTOR_IN2 12
#define BACK_LEFT_MOTOR_PWM 13
#define BACK_LEFT_MOTOR_ECA 14
#define BACK_LEFT_MOTOR_ECB 15

#define BACK_RIGHT_MOTOR_IN1 21
#define BACK_RIGHT_MOTOR_IN2 20
#define BACK_RIGHT_MOTOR_PWM 19
#define BACK_RIGHT_MOTOR_ECA 16
#define BACK_RIGHT_MOTOR_ECB 17

#define DISTANCE_FROM_WHEELS_X 95.175   // mm
#define DISTANCE_FROM_WHEELS_Y 111  // mm